import { chromium } from '@playwright/test'
import assert from 'node:assert/strict'
import { mkdirSync } from 'node:fs'
mkdirSync('test-results', {recursive:true})
const browser=await chromium.launch({headless:true, ...(process.env.CHROMIUM_PATH ? {executablePath:process.env.CHROMIUM_PATH} : {})})
const page=await browser.newPage({viewport:{width:1440,height:1100}})
const errors=[];page.on('pageerror',e=>errors.push(e.message))
await page.goto('http://localhost:5173')
await page.screenshot({path:'test-results/desktop.png',fullPage:true})
assert.equal(await page.locator('.vehicle-card').count(),3)
await page.locator('.save-button').first().click()
await page.getByRole('button',{name:'Saved vehicles'}).click()
assert.equal(await page.locator('.vehicle-card').count(),1)
await page.reload();await page.getByRole('button',{name:'Saved vehicles'}).click()
assert.equal(await page.locator('.vehicle-card').count(),1)
await page.getByRole('button',{name:'Check a VIN',exact:true}).click()
await page.getByPlaceholder('Enter 17-character VIN').fill('INVALID')
await page.getByRole('button',{name:'Look up vehicle'}).click()
assert.equal(await page.locator('.form-error').count(),1)
await page.getByPlaceholder('Enter 17-character VIN').fill('WDDWF4JB0HR123456')
await page.getByRole('button',{name:'Look up vehicle'}).click()
await page.locator('.record-modal').waitFor()
assert.match(await page.locator('.quote-box').innerText(),/₦2,500/)
assert.match(await page.locator('.check-status').nth(1).innerText(),/18d overdue/)
await page.getByRole('button',{name:'Close passport'}).click()
await page.getByRole('button',{name:'Check a VIN',exact:true}).click()
await page.getByPlaceholder('Enter 17-character VIN').fill('1HGCM82633A123456')
await page.getByRole('button',{name:'Look up vehicle'}).click()
assert.match(await page.locator('.record-modal').innerText(),/Vehicle history record/)
assert.match(await page.locator('.quote-box').innerText(),/₦15,000/)
await page.getByRole('button',{name:'Close passport'}).click()
await page.getByRole('button',{name:'Dealer workspace'}).click()
await page.locator('input[name=vin]').fill('2T2BZMCA0JC123456')
await page.locator('input[name=mileage]').fill('20000')
await page.getByRole('button',{name:'Screen vehicle'}).click()
assert.match(await page.locator('.screen-result').innerText(),/45,000 km/)
await page.getByRole('button',{name:'Sell my car',exact:true}).click()
for(const [key,value] of Object.entries({vin:'1HGCM82633A123456',name:'Honda Accord',year:'2018',mileage:'65000',price:'12000000'}))await page.locator(`input[name=${key}]`).fill(value)
await page.locator('input[type=checkbox]').check()
await page.getByRole('button',{name:'Save application'}).click()
assert.match(await page.locator('.draft').innerText(),/Honda Accord/)
await page.goto('http://localhost:5173/v/2T2BZMCA0JC123456')
await page.locator('.record-modal').waitFor()
assert.match(await page.locator('.quote-box').innerText(),/₦0/)
await page.emulateMedia({media:'print'})
assert.equal(await page.locator('.main-shell').isVisible(),false)
await page.emulateMedia({media:'screen'})
await page.goto('http://localhost:5173')
await page.setViewportSize({width:390,height:844})
await page.screenshot({path:'test-results/mobile.png',fullPage:true})
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true)
await page.getByRole('button',{name:'Open menu'}).click()
await page.getByRole('button',{name:'Explore vehicles',exact:true}).click()
assert.equal(await page.locator('.sidebar.open').count(),0)
assert.deepEqual(errors,[])
console.log('PASS: discovery, saved persistence, VIN validation, freshness pricing, unknown records, dealer rollback, seller draft, direct links, print mode, mobile layout and navigation; no browser exceptions.')
await browser.close()
