import { chromium } from '@playwright/test'
import { mkdirSync } from 'node:fs'
import assert from 'node:assert/strict'
import sharp from 'sharp'
mkdirSync('test-results',{recursive:true})
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--disable-dev-shm-usage']})
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}})
 const errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto((process.env.TEST_BASE_URL||'http://localhost:5173')+'/verification')
 await page.getByRole('button',{name:'Start sandbox workflow'}).click()
 await page.getByLabel('Vehicle identification number').fill('1HGCM82633A123456')
 await page.getByRole('button',{name:'Get inspection quote'}).click()
 await page.getByRole('heading',{name:'₦18,000'}).waitFor()
 await page.getByRole('button',{name:'Request inspection',exact:true}).click()
 await page.getByRole('button',{name:'Simulate confirmation'}).click()
 await page.getByRole('heading',{name:'Ready for a field inspector.'}).waitFor()
 await page.getByRole('button',{name:'Dispatch & QA',exact:true}).click()
 await page.locator('.order-list-item').first().click()
 await page.getByLabel('Assigned inspector').selectOption({index:1})
 await page.getByRole('button',{name:'Assign inspection',exact:true}).click()
 await page.getByText('Switch to Field inspector to capture evidence and submit the report.').waitFor()
 await page.getByRole('button',{name:'Field inspector',exact:true}).click()
 await page.locator('.order-list-item').first().click()
 const photo=await sharp({create:{width:600,height:400,channels:3,background:'#b2cbb0'}}).jpeg().toBuffer()
 for(const slot of ['dashboard','pillar']){
   await page.getByLabel(`${slot} evidence photo`).setInputFiles({name:'test-photo.jpg',mimeType:'image/jpeg',buffer:photo})
   await page.waitForResponse(r=>r.url().includes('/evidence?slot='+slot)&&r.status()===200)
   await page.getByLabel(`${slot} evidence photo`).isEnabled()
 }
 await page.getByLabel('Odometer (km)').fill('65000')
 await page.getByLabel('OBD-II codes & readiness').fill('P0420 pending. ABS was not scanned.')
 await page.getByLabel('Chassis & flood observations').fill('No visible welding in accessible areas. Underbody not lifted.')
 await page.getByLabel('Paint depths & panels').fill('Hood 230 microns; left door 135 microns.')
 await page.getByLabel('Vehicle condition outcome').selectOption('clear')
 await page.getByLabel('OBD-II inspection outcome').selectOption('issue')
 await page.getByLabel('These observations match the evidence.').check()
 await page.getByRole('button',{name:'Submit for independent QA'}).click()
 await page.getByText('Switch to Dispatch & QA to review this submission.').waitFor()
 await page.getByRole('button',{name:'Dispatch & QA',exact:true}).click()
 await page.locator('.order-list-item').first().click()
 await page.getByLabel('Private QA note').fill('Both VIN images checked; preserve diagnostic issue.')
 await page.getByLabel('Public vehicle condition summary').fill('No visible chassis welding in accessible areas.')
 await page.getByLabel('Public obd-ii inspection summary').fill('P0420 pending. Further diagnostics required.')
 await page.getByLabel('Public limitations').fill('Sandbox observations only. Underbody and ABS not examined. No registry checks.')
 await page.getByLabel('I independently reviewed the evidence').check()
 await page.screenshot({path:'test-results/workflow-review.png',fullPage:true})
 await page.getByRole('button',{name:'Publish reviewed findings'}).click()
 await page.getByRole('button',{name:'Open published passport'}).click()
 await page.getByText('Issue observed',{exact:true}).waitFor()
 assert.equal(await page.locator('.published-finding').count(),2)
 assert.equal(await page.locator('.registry-grid strong').first().textContent(),'Unavailable')
 await page.screenshot({path:'test-results/workflow-passport.png',fullPage:true})
 const link=page.url()
 const anonymous=await browser.newPage()
 await anonymous.goto(link)
 await anonymous.getByText('Issue observed',{exact:true}).waitFor()
 assert.equal(await anonymous.locator('.published-passport img').count(),0)
 await anonymous.close()
 await page.emulateMedia({media:'print'})
 assert.equal(await page.locator('.pilot-header').isVisible(),false)
 await page.emulateMedia({media:'screen'})
 await page.setViewportSize({width:390,height:844})
 await page.screenshot({path:'test-results/workflow-mobile.png',fullPage:true})
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)
 await page.getByRole('button',{name:'Workspace',exact:true}).click()
 await page.getByRole('button',{name:'Buyer',exact:true}).click()
 await page.getByLabel('Vehicle identification number').fill('1HGCM82633A123456')
 await page.getByRole('button',{name:'Get inspection quote'}).click()
 await page.getByRole('heading',{name:'₦0'}).waitFor()
 await page.reload()
 await page.getByRole('heading',{name:'Before you commit, check.'}).waitFor()
 await page.locator('.order-list-item').first().waitFor()
 assert.equal(await page.locator('.order-list-item').count(),1)
 assert.deepEqual(errors,[])
 console.log('PASS: browser quote → order → confirmation → assignment → image upload → report → QA → public passport; adverse outcome, anonymous share, print, mobile width, free reuse and reload persistence.')
} finally { await browser.close() }
